### PR TITLE
Merging into Main

### PR DESCRIPTION
**Pull request by csm-stough**

### CODE REVIEW

**Comment by csm-stough** [comment]
I've seen some comments in the discord that this issue is popping up regarding the `System.ConfigurationManager` getting flagged as an unused import.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@csm-stough  sorry about the delay.

At the moment the project doesn't load, as the ConsoleUtilities dependency wasn't checked into the repository. Could you please have a look?

image

**Comment by TheCSharpAcademy** [comment]
@csm-stough Hi there! Well done! The calendar view looks really cool! 😁 I'll approve it, but It would have been good if the users could also visualize a list of records. Other than that, all good! Congrats!

**Comment by csm-stough** [comment]
Thanks, I did try to make the calender alittle more informative, but
ConsoleTableExt seems to not like it when these cells have a multi-line
text

**Pull request merged**
