### PR TITLE
ThePortugueseMan.CodingTracker

### PR DESCRIPTION
**Pull request by ThePortugueseMan**

### CODE REVIEW

**Comment by ThePortugueseMan** [comment]
Codacy says I dont't need System.Configuration to access the COnfigurationManager which is not true, that's why the check failed

**Comment by TheCSharpAcademy** [comment]
> Codacy says I dont't need System.Configuration to access the ConfigurationManager which is not true, that's why the check failed

True! Codacy does that sometimes 😟

**Comment by TheCSharpAcademy** [comment]
@ThePortugueseMan Hey there! Well done! Very impressed with the project 😃

I'm approving it now but I'd just like to comment that ideally you should tell the user what's the minimum time that session should have to be registered: 

image

**Comment by ThePortugueseMan** [comment]
Thanks for the kind words! 😃

I added that information in a new commit!

Thanks for the review!

**Pull request merged**
