### PR TITLE
CodingTracker by kalsson

### PR DESCRIPTION
**Pull request by kalsson**
Finished with the CodingTracker project.

### CODE REVIEW

**Comment by BBualdo** [comment]
Hello @kalsson. I will be reviewer for your project.

For now I bumped into problem when I deleted all records from db, application freezes upon every option except inserting. Try to find a problem on your own first. If you can't, let me know 😁

**Comment by BBualdo** [comment]
Hello @kalsson. I will be your reviewer for this project.

I bumped into problem when trying to view sessions. I will let you find it out by yourself. If you can't let me know and I will help 😁

**Comment by kalsson** [comment]
Hey,

I have tried creating new records, deleting them, updating them and I have no problems with it at all. Nothing in the program freezes.


Mvh,

Jonas



________________________________
Från: Sebastian ***@***.***>
Skickat: den 15 maj 2024 09:29
Till: TheCSharpAcademy/CodeReviews.Console.CodingTracker ***@***.***>
Kopia: Jonas Karlsson ***@***.***>; Mention ***@***.***>
Ämne: Re: [TheCSharpAcademy/CodeReviews.Console.CodingTracker] CodingTracker by kalsson (PR #95)


Hello @kalsson<https://github.com/kalsson>. I will be your reviewer for this project.

I bumped into problem when trying to view sessions. I will let you find it out by yourself. If you can't let me know and I will help 😁

**Comment by kalsson** [comment]
Hey @BBualdo 😁

I have tried creating new records, deleting them, updating them and I have no problems with it at all. Nothing in the program freezes.

**Comment by kalsson** [comment]
Hmm, can it be that I don't use asynchronous database operations on my CRUD?

**Comment by kalsson** [comment]
> Try to remove all data from database and then call View Sessions

I have sended you a video on Discord that showcase that the application never freeze on my end.

**Comment by BBualdo** [comment]
Consider cases where error leads to returning to main menu instantly with help of Console.ReadKey() and everything will be perfect 😁 Good job! 🎉

**Pull request closed without merging**
