### PR TITLE
Finished Coding Tracker - SCM42

### PR DESCRIPTION
**Pull request by SCM42**
Looking for feedback on how best to implement exception handling. I'm finding a lot of conflicting info on when to add them or even if I should.

### CODE REVIEW

**Comment by SCM42** [comment]
Need the Using System.Configuration that codeacy is flagging.

**Comment by ukpagrace** [comment]
Hi @SCM42 
I tried running the code and I came across this error
`
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\USER\Documents\codereview\CodeReviews.Console.CodingTracker\Coding Tracker\bin\Debug\net8.0\fonts\larry3d.flf.txt'.'`

**Comment by ukpagrace** [comment]
> Looking for feedback on how best to implement exception handling. I'm finding a lot of conflicting info on when to add them or even if I should.

your use of exception handling was fine, They can be used when calling the db, external APIs, or libraries. When an error can be thrown for whatever reason(bad user input, syntax error, etc), it ensures the application doesn't crash.

but if you know the error beforehand you can handle that instead of throwing an exception.

**Comment by ukpagrace** [comment]
Very nice project overall, your feature addition looks good.
I particularly liked the coding goals view and the asterisk on the date indicating done, along side the filtering section.

However,  
I ran into some errors when running your code 

1)The fonts folder wasn't copied to the output directory,
2) Using Visual Studio the output console wasn't showing because of the space used in the directory. Did you use vscode?

Also, you mentioned in the challenges section of your readMe file that you are unsure when to validate user input. However, after running your code with various invalid inputs, I found that the input validation effectively prevented unexpected data from being processed. This ensured that the user didn't provide inputs that the system was not expecting, which is the essence of input validation.

Overall Great Project and Weldone

**Comment by SCM42** [comment]
Hi! Yes, I did use VS Code for this. I'm very new at working with fonts and
absolute/relative paths and am having a difficult time getting it to see
the path to the file. The fonts folder was included with the project when I
submitted it but, I guess I need to change the path? Also, thank you for
your feedback on the exception handling.

**Comment by SCM42** [comment]
I updated the csproj file to load the fonts folder. I think it should work now?

**Comment by TheCSharpAcademy** [comment]
@ukpagrace Was this project approved? 😁

**Comment by ukpagrace** [comment]
> @ukpagrace Was this project approved? 😁

Yes I approved it.

**Comment by ukpagrace** [comment]
closing pull request

**Pull request closed without merging**
