### PR TITLE
Finished readme

### PR DESCRIPTION
**Pull request by GitNach**

### CODE REVIEW

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @GitNach 👋,

Firstly, well done on another project submission 🎉 

At this point in your journey you should really be adhering to the [submission guidelines](https://thecsharpacademy.com/article/52/code-reviews).

Please could you re-structure your project correctly?
Rename the folder and re-locate the README file inside it:
```
.
└── CodingTracker.GitNach/    <-- Rename
    ├── CodingTracker/
    ├── Controller/
    ├── Model/
    ├── View/
    ├── README.md              <-- Move
    └── CodingTracker.sln
```

Commit and push your changes and I will continue my review 🔧.

Thanks
@chrisjamiecarter

**Comment by GitNach** [comment]
I've relocated the README and added .GitNach to the folder, hope it's okay!

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @GitNach 👋,

Well done on getting the updates pushed 🎉 

I have performed a peer review and have some praise, as well as a few suggestions:

🟢 **Challenges**
Fantastic ⭐.
I love your timer/stopwatch implementation.

🟢 **README File**
Well done on a perfect readme file with great content 🥇 .

🟢 **Code Principles**
Outstanding work in implementing SOLID, DRY and KISS principles 🥈 .

🟢 **Solution Structure**
Well done (for now) having the correct solution structure 🥉 .
This makes it easier for code-reviewers to pull down and review your code.

🟠 **Style Guide Compliance**
Remember that when you have finished a project, give it a polish pass ✍️.
Pay attention to any code conventions in place, in this instance refer to the C# Academy's [code-conventions](https://thecsharpacademy.com/article/58/code-conventions) page.
This is important as good code conventions/styling ensures consistency, makes your code easier for others to read and maintain, and improves your chances of getting a pull request reviewed and approved.

🟠 **User Experience**
When updating/deleting a `CodingSession`, give the user a visual aid to help choose an ID 🖥️.
Display the list of records to choose from. You can use `Spectre.Console` to paginate the list if too long, and also to select the record rather than user input the ID. Also when updating, show the record being updated, or give the option to retain the existing value.

🟠 **Input Validation**
Currently you can input an end time that is less than the start time - impossible right? Except for time travelers 😄.

🟠 **Night Owls**
What do I do if I want to add a manual entry and I have been coding past midnight and into the next day? 🦉.

🔴 **Missing Requirement**
Unfortunately you are missing the below requirement. It looks like the building blocks are there, you just haven't implemented it.
- [ ] You'll need to create a configuration file that you'll contain your database path and connection strings.


**Please revisit to implement the missing requirement.**


Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘.

Thanks and good luck 🍀 ,
@chrisjamiecarter

**Comment by GitNach** [comment]
Hey @chrisjamiecarter !
I've applied the changes to the time input and the config file, for the config i've used the System.Configuration but the Codacy analysis says it's an unused using statement.

**Review by chrisjamiecarter — APPROVED** [review]
Thanks @GitNach,

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter

**Pull request closed without merging**
