### PR TITLE
Project finished

### PR DESCRIPTION
**Pull request by KroksasC**
Hello, looking forward for review!:)

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@KroksasC Thanks for submitting! 😄Looks like you're using .NET Framework? Why this monstrosity?😢

**Comment by KroksasC** [comment]
I always used it for console apps, there was like 2 options "Console App" and "Console App (.NET framework)" in visual studio 2022 so i always chose second one, if there is any need i can recreate in "Console App". I'm kind of new to programing so i didn't know difference between them.

**Comment by TheCSharpAcademy** [comment]
@KroksasC .NET Framework is what preceded .NET Core. It's only used in legacy apps. I can't build the project because I don't have installed in my computer. You can create a Console app with the latest version of .NET and copy your code into it 😄. You might need to tweak the code a bit but it should work

**Comment by KroksasC** [comment]
It shows that there are some issues, but it asks me to fix something that needs to be in my code

**Comment by TheCSharpAcademy** [comment]
@KroksasC  Project approved! 😄✅ It's a shame you didn't complete the challenges this time. 😟 It's always a good use of your time!  

Here, why not use autoproperties? 🤔
image

🗺️Don't forget you need to submit your Free Code Camp certificate to get your 🟩🟩 Olive Green Belt. [You can see the requirements for each belt here](https://thecsharpacademy.com/dashboard/roadmap). 

Oh and if possible join our Discord Community and add your username [to your profile](https://thecsharpacademy.com/dashboard/profile) so you can be part of the community as well. 😁

Looking forward to seeing your next projects! 😄

**Pull request closed without merging**
