### PR TITLE
First try

### PR DESCRIPTION
**Pull request by kakurokan**

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@kakurokan well done! I like the spinner in between actions 😁

For future projects, could you please:

- Not use a comma when naming your project. Use a period instead: 
image

- Remove all unnecessary empty lines (i.e. line 125 or 126 can be removed):
image

**Comment by TheCSharpAcademy** [comment]
@kakurokan voce e brasileiro? 😁 Mineiro aqui.

**Comment by kakurokan** [comment]
Opa!!! Sou sim, baianoKKKKK

**Comment by kakurokan** [comment]
Que daora mano, não esperava que fosse brasileiro

**Pull request merged**
