### PR TITLE
Project solution - 1/4 challenges completed

### PR DESCRIPTION
**Pull request by tonyissa**
Enjoyed organizing and applying basic OOP principles on this one, though not sure if I did the greatest job on that front. Also not great at design so making it look pretty is challenging, so I just resorted to using only a little bit of the Spectre features and markup.

For the challenges, I included a recorder/stopwatch function.

### CODE REVIEW

**Comment by tonyissa** [comment]
I think Codacy is bugging here with the unused 'using' issue, since `using System.Configuration` is necessary for my application to compile

**Comment by TheCSharpAcademy** [comment]
@tonyissa Well done! The project is super well organized and following "Clean Code" and "Single Responsability" principles.  The UI and UX are solid. Great work! 👌🏻✅

A few things I'd like to point out:
1 - When you use static classes you're not really using OOP. Since the classes are available through the lifetime of the app, you aren't creating instances (or objects). Although you're using classes, methods and access modifiers correctly, I suggest you refrain from using "static" in most classes in the next project to expand your knowledge of OOP 🤓

2 - You check a few unnecessary files in. Make sure you only submit relevant files from now on 👌🏻😁
image

**Comment by TheCSharpAcademy** [comment]
@tonyissa Also make sure you submit your Free Code Camp certificate, you should already be Olive Green belt but you only progress if you complete all steps.

I also suggest you join us on Discord and [add your username to your profile](https://thecsharpacademy.com/dashboard/profile) in the dashboard so you can interact with the community 😎

**Comment by tonyissa** [comment]
> @tonyissa Also make sure you submit your Free Code Camp certificate, you should already be Olive Green belt but you only progress if you complete all steps.
> 
> I also suggest you join us on Discord and [add your username to your profile](https://thecsharpacademy.com/dashboard/profile) in the dashboard so you can interact with the community 😎

Done! I completed it but didn't realize I had to submit it. Also thanks for the feedback on the project. I have no idea where those files came from to be honest, I guess VS made them? But I will add them to my .gitignore next time or remove those files if they're cached.

**Pull request closed without merging**
