### PR TITLE
ready for a pull request

### PR DESCRIPTION
**Pull request by czerviik**
I'm  really sorry I messed up with the initial repository setting and commited to branch master instead of main, so I have to restructuralize my folders and merge it to main. If that's a problem I can create a new fork and just copy my project folder there.

### CODE REVIEW

**Comment by stevietv** [comment]
Hi @czerviik - I've picked up your project submission to review, but right now I'm having troubles with your menu, its throwing the following error when trying to add a new coding session manually:

```
Unhandled exception. System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 21.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at CodingTracker.UserInterface.ConsoleClearLines(Int32 clearFromLine) in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\UserInterface.cs:line 356
   at CodingTracker.UserInterface.SetSessionTime(Boolean isStart, Boolean isUpdate) in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\UserInterface.cs:line 31
   at CodingTracker.SetSessionMenu.SetDateTime() in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\Menu.cs:line 722
   at CodingTracker.SetSessionMenu.Display() in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\Menu.cs:line 678
   at CodingTracker.MenuManager.DisplayCurrentMenu() in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\MenuManager.cs:line 20
   at CodingTracker.MenuManager.NewMenu(Menu menu) in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\MenuManager.cs:line 27
   at CodingTracker.CodingSessionMenu.Display() in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\Menu.cs:line 51
   at CodingTracker.MenuManager.DisplayCurrentMenu() in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\MenuManager.cs:line 20
   at CodingTracker.MenuManager.NewMenu(Menu menu) in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\MenuManager.cs:line 27
   at CodingTracker.MainMenu.Display() in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\Menu.cs:line 25
   at CodingTracker.MenuManager.DisplayCurrentMenu() in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\MenuManager.cs:line 20
   at CodingTracker.MenuManager..ctor(Database database) in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\MenuManager.cs:line 12
   at CodingTracker.Program.Main(String[] args) in E:\Development\study\CSharpAcademy\CodeReviews.Console.CodingTracker\CodingTracker.czerviik\Program.cs:line 19

```

I've noticed that you've also put a lot of work into designing your own menu system. Very admirable, however you may want to take a deeper dive into spectre.console and see that it also has great options for menus for example using a [selectionprompt](https://spectreconsole.net/prompts/selection)

Drop me a note when you've managed to take

**Comment by czerviik** [comment]
Hey thanks for reviewing! I haven't got the console buffer issue probably because I'm running unix console on Mac, I haven't checked it on Windows. So I deleted the fixed console size, but can't test it on Windows right now. Pls let me know if it solved the issue. If not, I have to take some time to fix it for Win.

Also yes, I tried to design it myself, just for the means of challenge. When I started working with the spectre.console (tables) later in the project, I realized it could've been done probably easier. 

The repo should be now updated.

**Comment by stevietv** [comment]
Hey! thanks for making some changes. I'm still getting the same error on lines like this ` Console.SetCursorPosition(0, currentIndex);`

It indeed could be an issue with Mac vs Windows - I'll call in Pablo (@TheCSharpAcademy) to see if he can advise!

**Comment by czerviik** [comment]
Hi, yes, I'm pretty sure it's the OS issue, that sucks. Should I contact Pablo on Discord?

**Comment by stevietv** [comment]
I discussed this with Pablo and he told me to go ahead and review your code by making a few adjustments.
I removed the contents of these two methods, which were causing the issue:

https://github.com/czerviik/CodeReviews.Console.CodingTracker/blob/7048afaec3267ba0fe5bc5c54df5f0ff26785972/CodingTracker.czerviik/UserInterface.cs#L352-L373

With those removed I was able to run the app, and see that you did really nicely. You met all the challenges so well done!
A few things that could be improved:
* provide a way for the user to cancel deleting or adding a record, in case they change their mind. (like c for cancel, e for exit or something)
* display the list of records once in the delete menu
* try out next time to use Spectre.console for generating your menus, no need to write the ui yourself when that library can do it, ensuring is not tied to a specific console architecture

Great work! sorry about the hold up on the review!

**Review by stevietv — APPROVED** [review]

**Comment by czerviik** [comment]
Hey Stevie, thanks for approvement and suggestions! 

- About the cancelation during entering a record data, there's a feature that you can press Escape anytime to go back (even when typing into the console). It should work also when picking a menu choice, Escape always leads back to previous Menu. 

- Not sure what you mean by displaying all records once in delete menu. When the records are shown (filtered or not) you can choose Delete and select your record by Id. 

- definitely agree! the spectre console handles the options lists much better, I'm using it now in the Flashcard project and it's very smooth!

**Pull request closed without merging**
