### PR TITLE
review

### PR DESCRIPTION
**Pull request by vilvee**

### CODE REVIEW

**Comment by vilvee** [comment]
I think this is incorrectly flagged for System.Configuration

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@vilvee Thanks for submitting! It's good that you're checking if the end time comes after the start time, but the exception you're throwing remains unhandled, so the app is crashing. 

image

**Comment by TheCSharpAcademy** [comment]
@vilvee Let me know if you need help 😊

**Comment by TheCSharpAcademy** [comment]
@vilvee I'm closing the PR for admin purposes, feel free to reopen and resubmit when you're ready 😎

**Pull request closed without merging**
