### PR TITLE
Coding Tracker Project

### PR DESCRIPTION
**Pull request by ColdSummer8**
Hello,

I've completed the coding tracker project. 
Thank you for reviewing my code.

### CODE REVIEW

**Comment by Jinboi** [comment]
Hey @ColdSummer8 ,

Thank you for submitting your project.

Your project looks great but there were some minor issues that I ran to.

1. End < Start Date

image

I could update the existing data entry so that the end date is earlier than start date, resulting negative duration. 

2. Validation.cs

One of the requirements for this project is separation of concerns. You should move validation methods in a sperate class.

"You're required to have separate classes in different files (ex. UserInput.cs, Validation.cs, CodingController.cs)" 

3. Dapper

Another requirement was to use Dapper. Did you use Dapper?

"You need to use Dapper ORM for the data access instead of ADO.NET. (This requirement was included in Feb/2024)"

4. List of Coding Sessions

Another requirements was to read from a list of coding sessions. I could be wrong (as I'm quite new to this) but are you reading your table into a List of CodingSessions? 

"When reading from the database, you can't use an anonymous object, you have to read your table into a List of Coding Sessions."

Please let me know if you have any questions! Thank you! Cheers! 

-Youngwoo

**Comment by ColdSummer8** [comment]
Hello @Jinboi 

Thanks for the feedback.

1. I've updated the code to rectify the issue where the start date could be greater than the end date.
2. I've created a separate validation class file and create three new methods. Does this count?
3. I've only got knowledge with EF Core and if it is not too much to ask, could you please have a look whether what i wrote works? If you are not able to approve this because i did not use Dapper, that is totally find by me.
4. I used IQueryable<CodingSession> codingSession = db.Sessions to obtain all my data. If i'm not mistaken IQueryable and List both implements IEnumerable. Does that count as reading from a list of coding session? or do i need to turn my IQueryable into a list to satisfy the requirement?

Thanks again for your time and effort.
Sincerely,
ShengWei

**Comment by ColdSummer8** [comment]
Hello @Jinboi

Thanks for the feedback.

1. I've updated the code to rectify the issue where the start date could be greater than the end date.
2. I've created a separate validation class file and create three new methods. Does this count?
3. I've only got knowledge with EF Core and if it is not too much to ask, could you please have a look whether what i wrote works? If you are not able to approve this because i did not use Dapper, that is totally find by me.
4. I used IQueryable codingSession = db.Sessions to obtain all my data. If i'm not mistaken IQueryable and List both implements IEnumerable. Does that count as reading from a list of coding session? or do i need to turn my IQueryable into a list to satisfy the requirement?
Thanks again for your time and effort.
Sincerely,
ShengWei

**Comment by ColdSummer8** [comment]
Hello @Jinboi 

Thanks for the feedback.

1. I've updated the code to rectify the issue where the start date could be greater than the end date.
2. I've created a separate validation class file and create three new methods. Does this count?
3. I've only got knowledge with EF Core and if it is not too much to ask, could you please have a look whether what i wrote works? If you are not able to approve this because i did not use Dapper, that is totally find by me.
4. I used IQueryable<CodingSession> codingSession = db.Sessions to obtain all my data. If i'm not mistaken IQueryable and List both implements IEnumerable. Does that count as reading from a list of coding session? or do i need to turn my IQueryable into a list to satisfy the requirement?

Thanks again for your time and effort.
Sincerely,
ShengWei

**Comment by Jinboi** [comment]
@ColdSummer8 

Thanks for making the tweaks. Yeah—I won't be able to approve this project unless Dapper was used unless Pablo says otherwise.

But your project seems to be working flawlessly so Koodos to you on that! Thank you!

**Comment by TheCSharpAcademy** [comment]
@ColdSummer8 Please let us know if you'll complete the project so we can give the reviewer points to @Jinboi. Also, feel free to continue submitting your code even if you're not willing to complete this project. You'll still be reviewed and get points, you just won't participate in the belt system. 👌🏻😁

**Comment by ColdSummer8** [comment]
@TheCSharpAcademy I won't be completing this project. However, i will still submit future projects. 

on a side note, can @Jinboi still get the reviewer points even if i do not submit the Coding Tracker project? after all, he have reviewed my project. =D

**Comment by TheCSharpAcademy** [comment]
@ColdSummer8 Absolutely. I'll mark it as archived and he'll get the points. Feel free to resubmit if you want to resume the roadmap 👌🏻👌🏻

**Pull request closed without merging**
