### PR TITLE
Finished

### PR DESCRIPTION
**Pull request by Theosxenos**
Thanks again!

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
Can you please fix codacy issues

**Comment by Theosxenos** [comment]
The codacy issues are wrong. The first issue, I need the using statement in my configuration.cs for the configuration manager to work. The code in the other issue is not an empty statement and actually used to show a table for the sessions. However, I can try some changes to make the checks pass if it that is required to pass the exercise.

**Comment by Doc415** [comment]
> The codacy issues are wrong. The first issue, I need the using statement in my configuration.cs for the configuration manager to work. The code in the other issue is not an empty statement and actually used to show a table for the sessions. However, I can try some changes to make the checks pass if it that is required to pass the exercise.

No thats not needed i ll check the code now

**Review by Doc415 — APPROVED** [review]
Good to go :) Looking forward for your next project.

**Pull request closed without merging**
