### PR TITLE
TheCSharpAcademy Coding Tracker

### PR DESCRIPTION
**Pull request by samggannon**
This pull request represents a fork of the original Code Tracker Tutorial repository, followed by a YouTube learning channel hosted by TCSA coupled with DIY challenges to elevate the learning experience. The primary goal of this contribution is to augment the existing tutorial with the students choice of an additional features for a more comprehensive learning experience.

### CODE REVIEW

**Comment by samggannon** [comment]
Codacy is suggesting I remove the 'using System.Configuration;' statements but I am actually referencing and depending on it in my project.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@samggannon Thanks for submitting! It's looking good!

A couple of issues.
1 - This requirement isn't met:
image

2 - There's conflicting info in regards to date format
image

3 - This isn't a big deal but it would be good to ask the user for the id without the need to press a key, when deleting/updating

4 - Unused code:
image

image (https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/assets/108711476/532d5b96-69a1-4941-b470-951294ef463a)

5 - This is optional, but you can remove an entire level of indentation by adding a semi-colon to your namespaces: 

![image

**Comment by samggannon** [comment]
I am experiencing the same issue with Codacy where it isn't recognizing that I am using the System.Configuration. when i remove this using statement, my Error List window blows up and warns me that "The name 'ConfigurationManager' does not exist in the current context.' on the lines that contains my connectionStrings.

**Comment by samggannon** [comment]
image

You should be able to see in the provided screenshot, that i have my timespan formated for a 12 hour clock, but it seeems it is interpreting incorrectly to a 24 hour clock as "22:00" would not be a valid time for a 12 hour clock and isValid would be false. I am unsure how this will behave on your machine.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@samggannon Very good! Thanks for the changes. 

There's just one more requirement not being met. End date can't be before start date:

image

**Pull request merged**
