### PR TITLE
Inital commit

### PR DESCRIPTION
**Pull request by Ramseis**
I know it's pretty messy. Didn't seem like a meaningful place to split out methods. This is mostly menu navigation without a ton of clear repetition.

### CODE REVIEW

**Comment by Ramseis** [comment]
I'm not sure if I'm not seeing an alternative using call to System.Configuration with a more narrow scope, but it looks like the remaining static analysis error hits basically everyone's project. False positive?

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Ramseis Impressive project, well done! I really like that I can change colors. It also checks most requirements. 

I'm going to ask you to check this requirement though, as it's a key learning point of this project: 
image

**Comment by TheCSharpAcademy** [comment]
> I'm not sure if I'm not seeing an alternative using call to System.Configuration with a more narrow scope, but it looks like the remaining static analysis error hits basically everyone's project. False positive?

Yup don't worry about it.

**Comment by TheCSharpAcademy** [comment]
@Ramseis Thanks for making the changes. I'm going to approve the project because the objective here isn't to slow you down, and you demonstrated to have a basic understanding of separation of concerns. However there's still too much going on in Program.CS. You could have put all operations against the database in a separate class and validation on a different one again. And each option in the menu ideally should call it's own method. 

Think of creating small testable classes that do one single thing, which makes the whole thing easier to read, test and debug. This is a good example: https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/tree/main/CodingTracker.kimfom01/CodingTrackerConsole.

For the next project (Flashcards), given the complexity of the requirements, the code will get messy very quickly if these principles aren't applied. I'll be a bit more strict on that one, but that will be for your benefit 😊😊

**Pull request closed without merging**
