### PR TITLE
Coding tracker console application

### PR DESCRIPTION
**Pull request by ananttuli**
The coding tracker console app requirements. (Except the challenges).
Getting 1 codacy README.md issue for some reason, can't seem to fix it.

Completed the following:
- [x] This application has the same requirements as the previous project, except that now you'll be logging your daily coding time.
- [x] To show the data on the console, you should use the "Spectre.Console" library.
- [x] You're required to have separate classes in different files (ex. UserInput.cs, Validation.cs, CodingController.cs)
- [x] You should tell the user the specific format you want the date and time to be logged and not allow any other format.
- [x] You'll need to create a configuration file that you'll contain your database path and connection strings.
- [x] You'll need to create a "CodingSession" class in a separate file. It will contain the properties of your coding session: Id, StartTime, Endxime, Duration
- [x] The user shouldn't input the duration of the session. It should be calculated based on the Start and End times, in a separate "CalculateDuration" method.
- [x] The user should be able to input the start and end times manually.
- [x] You need to use Dapper ORM for the data access instead of ADO.NET. (This requirement was included in Feb/2024)
- [x] When reading from the database, you can't use an anonymous object, you have to read your table into a List of Coding Sessions.

### CODE REVIEW

**Comment by Jinboi** [comment]
@ananttuli 

Hi Ananttuli!

Happy Friday! Hahaha

I think there are some issues with the codes you uploaded. Can you please fix the issue and re-submit? Thank you! 😄

Please see below:

Please fix the errors picked up by code analysis before I review your code. You can find instructions in item 6 of this article: https://www.thecsharpacademy.com/article/52/code-reviews. If you have any questions feel free to reply to this comment or reach out on Discord via the #codeReview channel

**Comment by ananttuli** [comment]
@Jinboi Happy Friday! There's 1 codacy issue caused due to the README file which I couldn't resolve. Seems like many others are encountering this README codacy issue as well, based on discord chats.

image

**Comment by ananttuli** [comment]
@Jinboi Codacy issues should be fixed now, I just converted my README from`.md` to `.rst` 😆

**Comment by ananttuli** [comment]
> @ananttuli
> 
> Hi Ananttuli!
> 
> Happy Friday! Hahaha
> 
> I think there are some issues with the codes you uploaded. Can you please fix the issue and re-submit? Thank you! 😄
> 
> Please see below:
> 
> Please fix the errors picked up by code analysis before I review your code. You can find instructions in item 6 of this article: https://www.thecsharpacademy.com/article/52/code-reviews. If you have any questions feel free to reply to this comment or reach out on Discord via the #codeReview channel

@Jinboi Codacy issues should be fixed now, I just converted my README from`.md` to `.rst` 😆

**Comment by Jinboi** [comment]
Yes thank you for doing that. 

My apologies, ananttuli, I must've missed the memo about the read.me issue on this. For the future reference, you don't need to worry about that.

I'll go ahead and review your codes shortly. Sorry about that!

**Comment by ananttuli** [comment]
> Yes thank you for doing that.
> 
> My apologies, ananttuli, I must've missed the memo about the read.me issue on this. For the future reference, you don't need to worry about that.
> 
> I'll go ahead and review your codes shortly. Sorry about that!

@Jinboi No worries, thanks for reviewing

**Comment by Jinboi** [comment]
Thank you for your patience

Your project looks great! 👍 
I'll mark it approved and please move on to the next project!  😄 Thank you!

**Comment by ananttuli** [comment]
> Thank you for your patience
> 
> Your project looks great! 👍 I'll mark it approved and please move on to the next project! 😄 Thank you!

Thanks for the feedback @Jinboi 🙇 Closing this PR now.

**Pull request closed without merging**
