### PR TITLE
CodingTracker Emgigas

### PR DESCRIPTION
**Pull request by Emgigas**

### CODE REVIEW

**Comment by BBualdo** [comment]
Hello @Emgigas . I will be reviewer for your project.

For now I bumped into problem when I deleted all records from db, application freezes upon every option except inserting. Try to find a problem on your own first. If you can't, let me know 😁

**Comment by Emgigas** [comment]
> Hello @Emgigas . I will be reviewer for your project.
> 
> For now I bumped into problem when I deleted all records from db, application freezes upon every option except inserting. Try to find a problem on your own first. If you can't, let me know 😁
> 
> And also mention your nickname in project folder, for example CodingTracker.Emgigas. I just reviewed your code and commented it in someone elses pull request 🤣

Hi @BBualdo, thank you for your review. Apologies I didn't respond sooner. I submitted this and was then overseas on business. 

Noted on adding my nickname, I'll do that in future!

As for the bug you found. I know how I can fix this. I did consider that it would crash if there were no records but thought as I was seeding the database that couldn't happen. I never considered someone would delete all the records 😅.

I'll add the fix now and add a comment once done, thanks! ☺️

KR,
Emgigas

**Comment by Emgigas** [comment]
Hi @BBualdo,

I've made some changes to my code now. You should find when there are 0 records in the database table that you are taken back to the main menu when selecting any option other than Input Record now.

Hope this passes the test!

Thanks,
Emgigas 😃

**Comment by BBualdo** [comment]
Hi @Emgigas, nice to hear from you!

I checked everything and now it's all good. Just one tip:
Use Console.Clear() more strategically, because console after few operations becomes a little messy 😁

Good job though, Approved!

**Pull request closed without merging**
