### PR TITLE
Coding Tracker app with all challenges.

### PR DESCRIPTION
**Pull request by arashi256**

### CODE REVIEW

**Comment by arashi256** [comment]
Codacy check is wrong - the using is required to reference ConfigurationManager.

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hey your project looks great.
Unfortunately there are some parts that needs attention :<

When i try to update or delete first record in the list, it throws exception
image

After i recorded two live sessions, i select "list last 7 days coding sessions" and it shows none of them
image

--suggestion--
it is better to format decimals to 2-3 places
image

--suggestion--
it is not a good idea to let user fiddle with DB
image

**Comment by arashi256** [comment]
Could not reproduce update/delete coding session Exception. Other things fixed + patch to cope with particularly long TimeSpans for coding session durations.

**Review by Doc415 — APPROVED** [review]
Nice work. Approving you project.

**Comment by Doc415** [comment]
Nice work . Approving your project.

**Pull request closed without merging**
