### PR TITLE
first two challenges done

### PR DESCRIPTION
**Pull request by broki1**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@broki1 Hey there! You submit your project with the .git folder inside it. So it was picked up as a submodule, which means I can't see the changes. Try removing the git folder and recommitting and if it doesn't work create another PR where your project's folder doesn't contain a .git folder. 

image

**Comment by TheCSharpAcademy** [comment]
@broki1 You can submit your own repository for review as well. Just reply to this comment with the link. 🤓

**Comment by broki1** [comment]
GitHub - broki1/coding_tracker github.com On Dec 16, 2023, at 6:51 PM, The C# Academy ***@***.***> wrote: @broki1 You can submit your own repository for review as well. Just reply to this comment with the link. 🤓 — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you were mentioned. Message ID: ***@***.***>

**Comment by TheCSharpAcademy** [comment]
@broki1 I'm closing the PR for admin purposes, but feel free to re-open and resubmit when you're ready 😊

**Pull request closed without merging**
