### PR TITLE
Coding Tracker First Initialization

### PR DESCRIPTION
**Pull request by smkP13**

### CODE REVIEW

**Comment by hasona23** [comment]
Hi @smkP13 . Good job 🎉 .
The project is really unique in terms of functionality and well done especially the coding session part but i wont to point out a few things. I'll split things into 3 categories Critical  Mild  Advice/Suggestion.

==Critical==
- First of all no readme file which is one of the requirements.
- When project name is "Todo list" it shows an error as sql cant create table names with whitespaces. so this leads to every feature regarding this project to be buggy and mal-functioning even though it was approved by input validation and shown in the list of project.
- Also when inputting time 
image
the error says project name error so does not make sense to user and format asked for is yyyy.mm.dd
while in the error is says yyyy-mm-dd (which is invalid )
- Readability. in the coding session class there is Duration, DurationCount, Total duration adding comments differentiating between them would be really helpful when reading code

==Mild==
- In validation of dates I can set start to today and end to yesterday
- Use Id instead of RowId (Most used like origin or main in github)
- File naming. UserInputs.cs => InputHandler.cs | DataTools => CodingSessionController or CodingSessionDB(But then remove from controller direcotry)
- Also i suggest you rename the DatabaseAndConnectionString() method to Init()/Initialise() or something Clearer. 
- Also static classes remain till end of program so you might make DB non-static and use dependency injection to pass it around
- Lastly try to make function a little smaller by seprating individual function to smaller ones and if parts of function are not reusable and want to be private you can use Local Functions

==Suggestions==
- In coding session i think you can merge startDate and startHour and same goes to endDate and endHour
- Can make duration dynamically calculated which will also reduce Db columns and easier to get data from it or add data.

==Honourable Mentions==
- I must say your project is really unique and good looking. you used Spectre.Console well for input / Data visualization / Text or prompts or errors or selecting options.
- the coding session feature is really well made and good use of json file to keep track of session even if closed app.
- The app has really great features to sum up.
Anyway incase you feel over worked on this project or fatigued just finishing the Critical errors will make you good to go.
Good luck 👍

**Comment by TheCSharpAcademy** [comment]
@hasona23 Thanks for reviewing! Could you please assign yourself to this project in the academy?

**Comment by hasona23** [comment]
I am assigned

**Comment by hasona23** [comment]
I am assigned

**Comment by TheCSharpAcademy** [comment]
@smkP13 Let us know if you need help 😁

**Comment by smkP13** [comment]
>
> Hi,
>

Sorry I have had a lot of things going on those last weeks. I didn't really
had time to focus on programmation but I should be back on track next week.

Thank you for your revision and your help!

**Comment by hasona23** [comment]
No problem. glad you are back😀

**Review by hasona23 — CHANGES_REQUESTED** [review]
Hi @smkP13  hope you are doing ok. 
unfortunately i cant accept this project still because 
1. Readme still isnt there it shows me the raw file contents. Make the File READEME.md not .txt

also here are some suggestion to make this better or for future project . 
1. The model 
image

in the model i noticed that you kept the date and time as string i suggest you merge the endtime and enddate in a single variable of type DateTime and save to database as string and when getting it just parse it.
Dont make the duration as string save some storage from the database and just make it caclulated dynamically since you will have the the start and end as DateTime not string then Duration = End - Start and that's it (Note here i made it as if you made the previous suggestion of merging the variables .)
also for durationCount and totalduration just make them as integer. this will make it even easier to get it from database as you wont have to change type. 

anyway doing the readme would make you good to go. 😄 😄 😄

**Comment by smkP13** [comment]
Hi,
Thank you for clarifying the model issue. I misunderstood it and therefore
didn't apply the changes last time.
I made Start and End as DateTime and Store everything in the db as TEXT.
I just didn't store TotalDuration as TimeSpan in C# as it will make me do
the same amount of parse. And it saves me a bit of work.
I hope I understood it correctly this time.^^

Thank you for your help!

**Comment by hasona23** [comment]
Congrats 🎉 🎉  .accepted

**Comment by TheCSharpAcademy** [comment]
@smkP13 Congratulations! You got your Olive Green Belt! 👏🏻🥳 Could you please add your Discord alias [to your profile](https://thecsharpacademy.com/dashboard/profile) so we can communicate over there as well? 🤓

**Pull request closed without merging**
